### ISSUE TITLE
Maximum fan speed

### ISSUE THREAD

**Issue by nuudlz** [UKSFM99/razer-laptop-control#1]
Blade 15' adv - early '19 (i7 8750H; RTX2080) - BIOS 1.04 EC 1.02

> echo 5300 > fan_rpm 

(from auto!)  fans will only go somewhat around 4600; executing the command again theyll ramp up to 5,3k (sometimes I've to execute the command twice)

**Comment by UKSFM99** [comment]
After some time dealing with packet traces. I think I know whats going on. The manual fan command is sent to the EC twice with a delay between commands. I've tried to mimic that now in the code so give it a try

**Comment by UKSFM99** [comment]
Confirmed fixed
