### ISSUE TITLE
kernel coding style should be followed

### ISSUE THREAD

**Issue by gregkh** [UKSFM99/razer-laptop-control#10]
As this is a Linux kernel driver, the proper coding style rules should be followed.

You can run scripts/checkpatch.pl with "--file" added to it to find the problems that need to be resolved, or I can submit a patch that does this as well (but it would touch almost every line of the driver files, and that's a bit rude of me to do without asking :)

**Comment by UKSFM99** [comment]
either way, I don't mind...

Being a second year student who's self taught himself C in about 3 months, my code is inherently going to be bad so I appreciate being pointed to help write better code :).

I'd say then if you want to, submit a patch please.

**Comment by gregkh** [comment]
Thanks.  All should now be almost fixed up with pull request #11

**Comment by UKSFM99** [comment]
Thanks a lot! :)...merged your PR
