### ISSUE TITLE
[BUG] Lost device after Manjaro update

### ISSUE THREAD

**Issue by remingtonlang** [UKSFM99/razer-laptop-control#16]
**Describe the bug**
Decembers update to Manjaro broke the device entries, they're now missing. I'm assuming this is related to the kernel upgrade. Prior to filing i deleted razercontrol.ko, rebuilt, and rebooted.

```
# pwd
/sys/module/razercontrol/drivers/hid:Razer laptop System control driver
# ls
bind  module  new_id  uevent  unbind
```

**To Reproduce**
Use: 
```uname -a
Linux blade 5.4.6-2-MANJARO #1 SMP PREEMPT Tue Dec 24 15:55:20 UTC 2019 x86_64 GNU/Linux```

**Comment by UKSFM99** [comment]
this would be because the driver currently has no DKMS support. that's being worked on and should be ready before the end of the week. 

once DKMS support is ready, I will update the install instructions.

**Comment by UKSFM99** [comment]
DKMS merged now. Try the driver now as per the new install instructions.
