### ISSUE TITLE
Trying to install new DKMS version and make driver_dkms produces error

### ISSUE THREAD

**Issue by nalin29** [UKSFM99/razer-laptop-control#18]
**Describe the bug**
Installing driver produces error: 
Installing kernel modules for DKMS
install -m 644 -v -D Makefile /usr/src/razercontrol-0.0.1/Makefile
removed '/usr/src/razercontrol-0.0.1/Makefile'
'Makefile' -> '/usr/src/razercontrol-0.0.1/Makefile'
install -m 644 -v -D dkms.conf /usr/src/razercontrol-0.0.1/dkms.conf
install: cannot stat 'dkms.conf': No such file or directory
make: *** [Makefile:30: driver_dkms] Error 1

**To Reproduce**
simply try to make driver_dkms

**Comment by UKSFM99** [comment]
Woops! Appears my .gitignore meant dkms.conf was not being added to the repo. That should be fixed now. Pull and try again :)

**Comment by nalin29** [comment]
That fixed it after I reinstalled kernel header and ran  dkms install
