### ISSUE TITLE
Razer Blade Pro 17 2019 device id

### ISSUE THREAD

**Issue by dagbdagb** [UKSFM99/razer-laptop-control#3]
My Razer Magical Thing On The PCIe bus is 
Bus 001 Device 003: ID 1532:0234 Razer USA, Ltd Razer Blade

so: 023*4* not 0233.

**Comment by dagbdagb** [comment]
Added my device to defines.h and razer_common.c, and fan control appears to work.

**Comment by UKSFM99** [comment]
Adding now :)

**Comment by UKSFM99** [comment]
can you also launch synapse and tell me what the maximum fan RPM is?

**Comment by UKSFM99** [comment]
done
