### ISSUE TITLE
keyboard reset to US?

### ISSUE THREAD

**Issue by dagbdagb** [UKSFM99/razer-laptop-control#5]
Looks like my keyboard layout gets reset when loading and/or configuring this driver?

**Comment by UKSFM99** [comment]
lol what the actual fuck. I suppose my issue is that my laptops keyboard is already in US...

This will be an interesting thing to solve

**Comment by dagbdagb** [comment]
Verified that it actually happens. When I load the driver, the mapping gets reset.
Fiddling with fan_rpm does not reset the keyboard mapping.

**Comment by nuudlz** [comment]
Can't confirm. 

RZR Blade 15 adv early '19 - QWERTZ (de) keyboard
Distro: Manjaro - 
Kernel: 5.4
Lang: en
Keyboard layout: de (only have 1 layout configured)

**Comment by dagbdagb** [comment]
Confirmed or not, I find the explanation that a new kernel driver taking responsibility for the hardware causes this, to be a reasonable one. If the driver is loaded prior to X starting, there should not be an issue.
