### ISSUE TITLE
Razer Blade 15 Early 19 - Synapse Balanced; Gaming; Creator Modes

### ISSUE THREAD

**Issue by nuudlz** [UKSFM99/razer-laptop-control#6]
Hey Ashcon,

here some traces from my Synpase.

Model: Razer Blade 15 Adv Early 2019 (Intel i7 8750H; RTX2080)
BIOS: 1.04 (1.05 Update available) 
EC: 1.02 (1.03 Update available)

File 1: Rzr-Blade15-Early19-Balanced-Creater-USB1.7.0.pcapng
Switched modes 10 times, starting on Balanced mode. Both mode were on Auto-Fan.

FIle 2: Rzr-Blade15-Early19-Balanced-Gaming-USB1.7.0.pcapng
Switched modes 10 times, starting on Balanced mode. Both mode were on Auto-Fan.

USB Port is 1.7.0 this time.

[RZR-Synpase-Modes-Traces.zip](https://github.com/UKSFM99/razer-laptop-control/files/4007389/RZR-Synpase-Modes-Traces.zip)

**Comment by UKSFM99** [comment]
shall take a look

**Comment by UKSFM99** [comment]
Found it

**Comment by UKSFM99** [comment]
try now :)
